server:
  port: 5555
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:phonebook
    username: sa
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
app:
  messages:
     saveSuccessMessage: Contact Record saved successfully....
     saveFailMessage: Failed to save Contact Record.. Please Try Again!!!!
      
      
